package com.mall.supplier.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class SupplierRegionSettings implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_supplier_region_settings.region_id
     *
     * @mbggenerated
     */
    private Integer regionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_supplier_region_settings.region_text
     *
     * @mbggenerated
     */
    private String regionText;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_supplier_region_settings.operate_date
     *
     * @mbggenerated
     */
    private Date operateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_supplier_region_settings.ret_zk
     *
     * @mbggenerated
     */
    private BigDecimal retZk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_supplier_region_settings.ret_date
     *
     * @mbggenerated
     */
    private Integer retDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table s_supplier_region_settings
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_supplier_region_settings.region_id
     *
     * @return the value of s_supplier_region_settings.region_id
     *
     * @mbggenerated
     */
    public Integer getRegionId() {
        return regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_supplier_region_settings.region_id
     *
     * @param regionId the value for s_supplier_region_settings.region_id
     *
     * @mbggenerated
     */
    public void setRegionId(Integer regionId) {
        this.regionId = regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_supplier_region_settings.region_text
     *
     * @return the value of s_supplier_region_settings.region_text
     *
     * @mbggenerated
     */
    public String getRegionText() {
        return regionText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_supplier_region_settings.region_text
     *
     * @param regionText the value for s_supplier_region_settings.region_text
     *
     * @mbggenerated
     */
    public void setRegionText(String regionText) {
        this.regionText = regionText == null ? null : regionText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_supplier_region_settings.operate_date
     *
     * @return the value of s_supplier_region_settings.operate_date
     *
     * @mbggenerated
     */
    public Date getOperateDate() {
        return operateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_supplier_region_settings.operate_date
     *
     * @param operateDate the value for s_supplier_region_settings.operate_date
     *
     * @mbggenerated
     */
    public void setOperateDate(Date operateDate) {
        this.operateDate = operateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_supplier_region_settings.ret_zk
     *
     * @return the value of s_supplier_region_settings.ret_zk
     *
     * @mbggenerated
     */
    public BigDecimal getRetZk() {
        return retZk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_supplier_region_settings.ret_zk
     *
     * @param retZk the value for s_supplier_region_settings.ret_zk
     *
     * @mbggenerated
     */
    public void setRetZk(BigDecimal retZk) {
        this.retZk = retZk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_supplier_region_settings.ret_date
     *
     * @return the value of s_supplier_region_settings.ret_date
     *
     * @mbggenerated
     */
    public Integer getRetDate() {
        return retDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_supplier_region_settings.ret_date
     *
     * @param retDate the value for s_supplier_region_settings.ret_date
     *
     * @mbggenerated
     */
    public void setRetDate(Integer retDate) {
        this.retDate = retDate;
    }
}