package com.mall.supplier.model;

import com.mall.supplier.enums.SupplierType;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class SupplierTypeSettings implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_supplier_type.supplier_type
     *
     * @mbggenerated
     */
    private Integer supplierType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_supplier_type.proportion_repayment
     *
     * @mbggenerated
     */
    private BigDecimal proportionRepayment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_supplier_type.operate_date
     *
     * @mbggenerated
     */
    private Date operateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table s_supplier_type
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_supplier_type.supplier_type
     *
     * @return the value of s_supplier_type.supplier_type
     *
     * @mbggenerated
     */
    public Integer getSupplierType() {
        return supplierType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_supplier_type.supplier_type
     *
     * @param supplierType the value for s_supplier_type.supplier_type
     *
     * @mbggenerated
     */
    public void setSupplierType(Integer supplierType) {
        this.supplierType = supplierType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_supplier_type.proportion_repayment
     *
     * @return the value of s_supplier_type.proportion_repayment
     *
     * @mbggenerated
     */
    public BigDecimal getProportionRepayment() {
        return proportionRepayment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_supplier_type.proportion_repayment
     *
     * @param proportionRepayment the value for s_supplier_type.proportion_repayment
     *
     * @mbggenerated
     */
    public void setProportionRepayment(BigDecimal proportionRepayment) {
        this.proportionRepayment = proportionRepayment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_supplier_type.operate_date
     *
     * @return the value of s_supplier_type.operate_date
     *
     * @mbggenerated
     */
    public Date getOperateDate() {
        return operateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_supplier_type.operate_date
     *
     * @param operateDate the value for s_supplier_type.operate_date
     *
     * @mbggenerated
     */
    public void setOperateDate(Date operateDate) {
        this.operateDate = operateDate;
    }

    public SupplierType getSupplierTypeEnum(){
        return SupplierType.getSupplierType(this.supplierType);
    }

    public String getSupplierTypeName(){
        return SupplierType.getSupplierTypeName(this.supplierType);
    }
}