package com.mall.supplier.dao;

import com.mall.supplier.model.SupplierTypeSettings;

public interface SupplierTypeSettingsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_supplier_type
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer supplierType);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_supplier_type
     *
     * @mbggenerated
     */
    int insert(SupplierTypeSettings record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_supplier_type
     *
     * @mbggenerated
     */
    int insertSelective(SupplierTypeSettings record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_supplier_type
     *
     * @mbggenerated
     */
    SupplierTypeSettings selectByPrimaryKey(Integer supplierType);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_supplier_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SupplierTypeSettings record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_supplier_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SupplierTypeSettings record);
}