package com.mall.supplier.dao;

import com.mall.mybatis.utility.PageBean;
import com.mall.supplier.model.SupplierRegionSettings;

import java.util.List;

public interface SupplierRegionSettingsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_supplier_region_settings
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer regionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_supplier_region_settings
     *
     * @mbggenerated
     */
    int insert(SupplierRegionSettings record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_supplier_region_settings
     *
     * @mbggenerated
     */
    int insertSelective(SupplierRegionSettings record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_supplier_region_settings
     *
     * @mbggenerated
     */
    SupplierRegionSettings selectByPrimaryKey(Integer regionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_supplier_region_settings
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SupplierRegionSettings record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_supplier_region_settings
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SupplierRegionSettings record);

    List<SupplierRegionSettings> selectAll();

    List<SupplierRegionSettings> selectByPageList(PageBean<SupplierRegionSettings> regionSettingsPageBean);
    List<SupplierRegionSettings> selectByPageListxfg(PageBean<SupplierRegionSettings> regionSettingsPageBean);

	int insertSelectivexfg(SupplierRegionSettings regionSettings);

	int deleteByPrimaryKeyxfg(Integer regionId);

	int updateByPrimaryKeySelectivexfg(SupplierRegionSettings regionSettings);

	SupplierRegionSettings selectByPrimaryKeyxfg(int regionID);
}